[package]
description = "Termio's UI Implementation"
name = "termio-ui"
version.workspace = true
edition.workspace = true

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
pixels = "0.15.0"
winit.workspace = true
